# Site settings
title: Marcelo Bohn Blog
email: marcelo.bohn@gmail.com
description: 
  Blog de tecnologia de desenvolvimento de sistemas
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marcelobohn.github.io/" # the base hostname & protocol for your site
twitter_username: marcelobohn
github_username:  marcelobohn

# Build settings
markdown: kramdown
